### ISSUE TITLE
Error with embedding

### ISSUE THREAD

**Issue by anuC** [ml4bio/Dense-Homolog-Retrieval#17]
Hi,

I am experiencing the following error while doing the embedding,

> (fastMSA) csl:~/Dense-Homolog-Retrieval$ python3 do_embedding.py trainer.ur90_path=/home/csl/D
ense-Homolog-Retrieval/Uniref90_db/uniref90.tsv model.ckpt_path=/home/csl/Dense-Homolog-Retrieval/dhr2_ckpt hydra.run.dir=/home/csl/Dense-Homolog-Retrieval/OUTPUT
Global seed set to 1234
/home/csl/Dense-Homolog-Retrieval/dhr2_ckpt
[2024-09-06 12:18:38,598][torch.distributed.nn.jit.instantiator][INFO] - Created a temporary directory at /tmp/tmptgxvq3q2
[2024-09-06 12:18:38,599][torch.distributed.nn.jit.instantiator][INFO] - Writing /tmp/tmptgxvq3q2/_remote_module_non_sriptable.py
Error executing job with overrides: ['trainer.ur90_path=/home/csl/Dense-Homolog-Retrieval/Uniref90_db/uniref90.tsv', 'model.ckpt_path=/home/csl/Dense-Homolog-Retrieval/dhr2_ckpt']
Traceback (most recent call last):
  File "do_embedding.py", line 56, in main
    trainer = pl.Trainer(
  File "/home/csl/miniconda3_INSTALL/envs/fastMSA/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/env_vars_connector.py", line 38, in insert_env_defaults
    return fn(self, **kwargs)
  File "/home/csl/miniconda3_INSTALL/envs/fastMSA/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 431, in __init__
    self._accelerator_connector = AcceleratorConnector(
  File "/home/csl/miniconda3_INSTALL/envs/fastMSA/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 161, in __init__
    self.select_accelerator_type()
  File "/home/csl/miniconda3_INSTALL/envs/fastMSA/lib/python3.8/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py", line 228, in select_accelerator_type
    raise MisconfigurationException(f"You passed `accelerator='gpu'`, but {msg}.")
pytorch_lightning.utilities.exceptions.MisconfigurationException: You passed `accelerator='gpu'`, but GPUs are not available.

>Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
(fastMSA) csl:~/Dense-Homolog-Retrieval$

Any help would be highly appreciated.

Thanks in advance

**Comment by heathcliff233** [comment]
Hello, it seems that your GPU is not available. Please make sure that you are on a machine with Nvidia GPU and created the environment correctly.
