### ISSUE TITLE
Offline Embedding ERROR

### ISSUE THREAD

**Issue by Flooooooooooooower** [ml4bio/Dense-Homolog-Retrieval#6]
Hi, I used Prokka to predict protein sequences from metagenomic data and now want to use DHR for protein homologue prediction. However, when I tried to embed the protein sequences generated by Prokka, I encountered the following error and I'm not sure what went wrong. I would greatly appreciate your help in resolving this issue. Additionally, I have another question: Could you please explain how to use the two models, dhr_cencoder.pt and dhr_qencoder.pt?
```
python3 /home/xxx/00.Software/Dense-Homolog-Retrieval/do_embedding.py trainer.ur90_path=/home/xxx/10.meta-genome/01.sheep_gut/05.DHR/sheep_gut.faa   model.ckpt_path=/home/xxx/00.Software/Dense-Homolog-Retrieval/dhr_cencoder.pt  hydra.run.dir=./test
/home/xxx/00.Software/Dense-Homolog-Retrieval/do_embedding.py:40: UserWarning:
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="conf", config_name="pred_conf")
/home/xxx/miniconda3/envs/fastMSA/lib/python3.9/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
Seed set to 1234
Error executing job with overrides: ['trainer.ur90_path=/home/xxx/10.meta-genome/01.sheep_gut/05.DHR/sheep_gut.faa', 'model.ckpt_path=/home/xxx/00.Software/Dense-Homolog-Retrieval/dhr_cencoder.pt']
Traceback (most recent call last):
  File "/home/xxx/00.Software/Dense-Homolog-Retrieval/do_embedding.py", line 80, in <module>
    main()
  File "/home/xxx/miniconda3/envs/fastMSA/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/xxx/miniconda3/envs/fastMSA/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/xxx/miniconda3/envs/fastMSA/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/xxx/miniconda3/envs/fastMSA/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/xxx/miniconda3/envs/fastMSA/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/xxx/miniconda3/envs/fastMSA/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/xxx/miniconda3/envs/fastMSA/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/xxx/miniconda3/envs/fastMSA/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/xxx/miniconda3/envs/fastMSA/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/xxx/00.Software/Dense-Homolog-Retrieval/do_embedding.py", line 55, in main
    model = MyEncoder.load_from_checkpoint(
  File "/home/xxx/miniconda3/envs/fastMSA/lib/python3.9/site-packages/pytorch_lightning/core/module.py", line 1552, in load_from_checkpoint
    loaded = _load_from_checkpoint(
  File "/home/xxx/miniconda3/envs/fastMSA/lib/python3.9/site-packages/pytorch_lightning/core/saving.py", line 64, in _load_from_checkpoint
    checkpoint = _pl_migrate_checkpoint(
  File "/home/xxx/miniconda3/envs/fastMSA/lib/python3.9/site-packages/pytorch_lightning/utilities/migration/utils.py", line 142, in _pl_migrate_checkpoint
    old_version = _get_version(checkpoint)
  File "/home/xxx/miniconda3/envs/fastMSA/lib/python3.9/site-packages/pytorch_lightning/utilities/migration/utils.py", line 163, in _get_version
    return checkpoint["pytorch-lightning_version"]
TypeError: tuple indices must be integers or slices, not str
```

**Comment by editSeqDesign** [comment]
I have the same problem

**Comment by editSeqDesign** [comment]
The feeling is that the version of pytorch lightning written in the model is inconsistent with the version of pytorch lightning read in

**Comment by heathcliff233** [comment]
Hello, thanks for trying. The yaml file to build the environment has been updated. The code base in main branch seems to corrupt with v1 branch, and I am currently cleanning it. Sorry for the inconvenience.

**Comment by heathcliff233** [comment]
The codebase has been updated and please try to pull again. Thank you.
